server:
  port: 8080

spring:
  application:
    name: library-admin-backend
  profiles:
    default: local
  jpa:
    open-in-view: false

app:
  auth:
    token-header: X-Student-Token
    admin-token-header: X-Admin-Token
  cors:
    allowed-origin-patterns: ${APP_CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost:5173,https://*.amplifyapp.com}
  datasource:
    enabled: false
  iot:
    enabled: false
  aws:
    enabled: false
